### ISSUE TITLE
Add page generator

### ISSUE THREAD

**Issue by pettersuul** [northofwine/northofwine-staging#2]
Add jekyll-datapage-generator plugin.

Settings:
```
page_gen-dirs: false
page_gen:
- data: contentful.spaces.northofwine.product
  template: product_detail
  dir: utvalg
  name: product_short_name
```
